export const pets = [
  {
    id: 1,
    name: "Bella",
    type: "Dog",
    breed: "Labrador",
    age: "2 years",
    gender: "Female",
    description: "Friendly and energetic dog, loves kids.",
    image: "https://images.unsplash.com/photo-1561495376-dc9c7c5b8726?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    keywords: ["dog", "friendly", "labrador", "family", "playful"],
  },
// 15553053262
  {
    id: 2,
    name: "Max",
    type: "Dog",
    breed: "German Shepherd",
    age: "3 years",
    gender: "Male",
    description: "Loyal and intelligent, great for an active home.",
    image: "https://images.unsplash.com/photo-1601180964879-e9cba08d8237?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGdlcm1hbiUyMHNoZXBoZXJkfGVufDB8MHwwfHx8MA%3D%3D",
    keywords: ["dog", "loyal", "smart", "german shepherd", "active"],
  },
  {
    id: 3,
    name: "Luna",
    type: "Cat",
    breed: "Domestic Shorthair",
    age: "1 year",
    gender: "Female",
    description: "Curious cuddle-bug who loves sunny windows and soft blankets.",
    image: "https://images.unsplash.com/photo-1602634353750-d58ec14064c6?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    keywords: ["cat", "cuddly", "curious", "calm", "indoor"],
  },
  {
    id: 4,
    name: "Charlie",
    type: "Dog",
    breed: "Beagle",
    age: "4 years",
    gender: "Male",
    description: "Sweet nose-on-the-ground explorer, friendly with everyone.",
    image: "https://images.unsplash.com/photo-1586917138540-f1490b02f205?q=80&w=936&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    keywords: ["dog", "beagle", "friendly", "curious", "outdoors"],
  },
  {
    id: 5,
    name: "Milo",
    type: "Cat",
    breed: "Maine Coon",
    age: "5 years",
    gender: "Male",
    description: "Gentle giant with a fluffy coat and a chill personality.",
    image: "https://images.unsplash.com/photo-1606047915827-b832c389a4e3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    keywords: ["cat", "maine coon", "fluffy", "gentle", "calm"],
  },
  {
    id: 6,
    name: "Daisy",
    type: "Dog",
    breed: "Golden Retriever",
    age: "2 years",
    gender: "Female",
    description: "Happy-go-lucky pup who loves fetch and belly rubs.",
    image: "https://images.unsplash.com/photo-1507149833265-60c372daea22?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "golden retriever", "playful", "friendly", "fetch"],
  },
  {
    id: 7,
    name: "Coco",
    type: "Rabbit",
    breed: "Holland Lop",
    age: "10 months",
    gender: "Female",
    description: "Quiet, gentle bunny who enjoys head rubs and leafy greens.",
    image: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=1200&q=80",
    keywords: ["rabbit", "holland lop", "gentle", "quiet", "small pet"],
  },
  {
    id: 8,
    name: "Rocky",
    type: "Dog",
    breed: "Mixed Breed",
    age: "1 year",
    gender: "Male",
    description: "Goofy, energetic, and learning fast. Ready for adventures.",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "mixed breed", "energetic", "goofy", "trainable"],
  },
  {
    id: 9,
    name: "Nala",
    type: "Cat",
    breed: "Siamese",
    age: "2 years",
    gender: "Female",
    description: "Chatty, affectionate, and loves being part of your day.",
    image: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=1200&q=80",
    keywords: ["cat", "siamese", "affectionate", "talkative", "social"],
  },
  {
    id: 10,
    name: "Buddy",
    type: "Dog",
    breed: "French Bulldog",
    age: "3 years",
    gender: "Male",
    description: "Compact cuddle machine. Great apartment companion.",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "french bulldog", "apartment", "cuddly", "easygoing"],
  },
  {
    id: 11,
    name: "Kiwi",
    type: "Bird",
    breed: "Budgerigar",
    age: "1 year",
    gender: "Male",
    description: "Bright, social little buddy who loves gentle whistling.",
    image: "https://images.unsplash.com/photo-1520808663317-647b476a81b9?auto=format&fit=crop&w=1200&q=80",
    keywords: ["bird", "budgie", "social", "small pet", "chirpy"],
  },
  {
    id: 12,
    name: "Zara",
    type: "Dog",
    breed: "Poodle",
    age: "6 years",
    gender: "Female",
    description: "Calm and clever, enjoys short walks and lots of love.",
    image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "poodle", "calm", "smart", "low shedding"],
  },
  {
    id: 13,
    name: "Simba",
    type: "Cat",
    breed: "Tabby",
    age: "3 years",
    gender: "Male",
    description: "Confident lap-cat who purrs like an engine and loves chin scratches.",
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=1200&q=80",
    keywords: ["cat", "tabby", "affectionate", "lap", "purring"],
  },
  {
    id: 14,
    name: "Pepper",
    type: "Dog",
    breed: "Border Collie",
    age: "2 years",
    gender: "Female",
    description: "Super smart and energetic, thrives with games, runs, and training.",
    image: "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "border collie", "smart", "energetic", "training"],
  },
  {
    id: 15,
    name: "Oliver",
    type: "Cat",
    breed: "British Shorthair",
    age: "4 years",
    gender: "Male",
    description: "Soft, calm companion who enjoys quiet rooms and steady routines.",
    image: "https://images.unsplash.com/photo-1606213651356-0272d8f818b2?auto=format&fit=crop&w=1200&q=80",
    keywords: ["cat", "british shorthair", "calm", "gentle", "indoor"],
  },
  {
    id: 16,
    name: "Hazel",
    type: "Rabbit",
    breed: "Mini Rex",
    age: "1 year",
    gender: "Female",
    description: "Velvety-soft bunny who loves hopping around and nibbling herbs.",
    image: "https://images.unsplash.com/photo-1555696958-c5049b866f6a?auto=format&fit=crop&w=1200&q=80",
    keywords: ["rabbit", "mini rex", "soft", "gentle", "small pet"],
  },
  {
    id: 17,
    name: "Thor",
    type: "Dog",
    breed: "Rottweiler",
    age: "5 years",
    gender: "Male",
    description: "Big teddy bear energy, loyal and calm with a protective streak.",
    image: "https://images.unsplash.com/photo-1560807707-8cc77767d783?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "rottweiler", "loyal", "calm", "protective"],
  },
  {
    id: 18,
    name: "Willow",
    type: "Dog",
    breed: "Cavalier King Charles Spaniel",
    age: "2 years",
    gender: "Female",
    description: "Gentle snuggle expert, perfect for cozy evenings and short walks.",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "cavalier", "gentle", "cuddly", "companion"],
  },
  {
    id: 19,
    name: "Bubbles",
    type: "Fish",
    breed: "Betta",
    age: "8 months",
    gender: "Male",
    description: "Vibrant solo swimmer with a flair for dramatic fin poses.",
    image: "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?auto=format&fit=crop&w=1200&q=80",
    keywords: ["fish", "betta", "colorful", "aquarium", "low space"],
  },
  {
    id: 20,
    name: "Snowy",
    type: "Dog",
    breed: "Samoyed",
    age: "2 years",
    gender: "Female",
    description: "Smiling fluff cloud who loves people and playful outdoor time.",
    image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "samoyed", "fluffy", "friendly", "outdoors"],
  },
  {
    id: 21,
    name: "Poppy",
    type: "Cat",
    breed: "Ragdoll",
    age: "2 years",
    gender: "Female",
    description: "Sweet, relaxed cat who goes limp in your arms and loves cuddles.",
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?auto=format&fit=crop&w=1200&q=80",
    keywords: ["cat", "ragdoll", "cuddly", "relaxed", "gentle"],
  },
  {
    id: 22,
    name: "Koda",
    type: "Dog",
    breed: "Husky",
    age: "3 years",
    gender: "Male",
    description: "Chatty adventure buddy with lots of personality and energy.",
    image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "husky", "energetic", "talkative", "adventure"],
  },
  {
    id: 23,
    name: "Mocha",
    type: "Dog",
    breed: "Dachshund",
    age: "1 year",
    gender: "Female",
    description: "Tiny but fearless, loves blankets, squeaky toys, and burrowing.",
    image: "https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "dachshund", "small", "playful", "burrow"],
  },
  {
    id: 24,
    name: "Gizmo",
    type: "Guinea Pig",
    breed: "American",
    age: "9 months",
    gender: "Male",
    description: "Gentle squeaker who loves veggies and cozy hideouts.",
    image: "https://images.unsplash.com/photo-1610737241336-371badac3b66?auto=format&fit=crop&w=1200&q=80",
    keywords: ["guinea pig", "small pet", "gentle", "friendly", "veggies"],
  },
  {
    id: 25,
    name: "Ruby",
    type: "Dog",
    breed: "Shih Tzu",
    age: "6 years",
    gender: "Female",
    description: "Sweet senior who enjoys calm company, grooming days, and naps.",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "shih tzu", "senior", "calm", "companion"],
  },
  {
    id: 26,
    name: "Onyx",
    type: "Cat",
    breed: "Bombay",
    age: "2 years",
    gender: "Male",
    description: "Sleek shadow-cat who follows you around like a little guardian.",
    image: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=1200&q=80",
    keywords: ["cat", "bombay", "sleek", "affectionate", "social"],
  },
  {
    id: 27,
    name: "Tango",
    type: "Dog",
    breed: "Corgi",
    age: "2 years",
    gender: "Male",
    description: "Short legs, big attitude, loves zoomies and being everyone’s friend.",
    image: "https://images.unsplash.com/photo-1546975490-8c11b3b9a1fd?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "corgi", "playful", "friendly", "zoomies"],
  },
  {
    id: 28,
    name: "Sage",
    type: "Bird",
    breed: "Cockatiel",
    age: "2 years",
    gender: "Female",
    description: "Curious whistler who enjoys gentle music and shoulder rides.",
    image: "https://images.unsplash.com/photo-1544923408-75c5cef46f14?auto=format&fit=crop&w=1200&q=80",
    keywords: ["bird", "cockatiel", "whistling", "social", "smart"],
  },
  {
    id: 29,
    name: "Bruno",
    type: "Dog",
    breed: "Boxer",
    age: "4 years",
    gender: "Male",
    description: "Goofy athlete who loves fetch, kids, and big happy grins.",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    keywords: ["dog", "boxer", "goofy", "active", "family"],
  },
  {
    id: 30,
    name: "Misty",
    type: "Cat",
    breed: "Persian",
    age: "5 years",
    gender: "Female",
    description: "Elegant floof who prefers calm vibes, soft brushing, and quiet naps.",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=80",
    keywords: ["cat", "persian", "fluffy", "calm", "indoor"],
  },
];
